/**
 * Source credibility, platform routing, and misinformation filtering.
 *
 * Two ideas drive this module:
 *
 * 1. A source's trust is a *derived* fact, not a label. The caller supplies
 *    observable evidence (is it the vendor's own domain? does the Bilibili
 *    account carry a blue lightning? did the account's title and bio actually
 *    mention toys/models?) and the module returns a tier with reasons.
 * 2. Anything unverifiable is surfaced, not averaged away. Accounts without a
 *    lightning bolt become a user-confirmation prompt, and single-source,
 *    AI-generated, or low-tier claims are marked display-only so they can never
 *    be filed into the knowledge base.
 * @module @dsh-plugin/tokusatsu-gunpla/sources
 */

import { fileURLToPath } from 'node:url'
import { dataPath, readJsonIfPresent, writeJsonAtomic } from './runtime.js'

/** Source tiers, highest trust first. `trust` is the ceiling for the tier. */
export const TIERS = [
  { id: 1, key: 'official-site', trust: 100, label: '厂商官网', note: '一手来源，可作为入库依据' },
  { id: 2, key: 'official-social-vpn', trust: 96, label: 'X / YouTube 官方号', note: '需 VPN，官方发布，可入库' },
  { id: 3, key: 'official-social-cn', trust: 92, label: '国内平台官方号（蓝闪电+认证主体+头像）', note: '三项齐全才按官方对待' },
  { id: 4, key: 'official-release-list', trust: 90, label: '官方发售列表', note: '商品线与发售日期的权威清单' },
  { id: 5, key: 'official-promo-video', trust: 85, label: '当年官号宣发视频', note: '老物的重要旁证' },
  { id: 6, key: 'major-retailer-wiki', trust: 70, label: '大型电商 / 主流维基', note: '可交叉，不单独入库' },
  { id: 7, key: 'era-post-blog', trust: 55, label: '当年帖子 / 博客', note: '时效性好，需与官方互证' },
  { id: 8, key: 'creator-yellow', trust: 45, label: '黄闪电 UP 主', note: '仅作参考' },
  { id: 9, key: 'creator-plain', trust: 30, label: '普通 UP 主', note: '仅作参考' },
  { id: 10, key: 'group-chat', trust: 12, label: '群聊 / 未署名转述', note: '只展示，不入库' },
]

/** Domains whose access requires a VPN from mainland China. */
export const VPN_DOMAINS = [
  'x.com', 'twitter.com', 'youtube.com', 'youtu.be', 'google.com', 'googleapis.com',
  'instagram.com', 'facebook.com', 'reddit.com', 'pixiv.net', 'amazon.co.jp', 'yahoo.co.jp',
]

/** Search engines by language market. Explicitly excludes 360/搜狗/2345. */
export const SEARCH_ENGINES = {
  zh: { engine: 'bing', region: 'cn', url: 'https://cn.bing.com/search?q=', note: '中文优先，结果最干净' },
  'zh-alt': { engine: 'baidu', region: 'cn', url: 'https://www.baidu.com/s?wd=', note: '百度结果必须在展示时标注「未认证」' },
  en: { engine: 'google', region: 'global', url: 'https://www.google.com/search?q=', note: '需 VPN' },
  ja: { engine: 'google', region: 'jp', url: 'https://www.google.com/search?q=', note: '需 VPN' },
  ru: { engine: 'yandex', region: 'ru', url: 'https://yandex.com/search/?text=', note: '俄语市场首选' },
}

/** Engines the product refuses to use, with the reason recorded for the UI. */
export const BANNED_ENGINES = [
  { engine: '360so', reason: '结果污染与劫持风险' },
  { engine: 'sogou', reason: '结果污染' },
  { engine: '2345', reason: '浏览器劫持与结果污染' },
]

/** Markers that a piece of content is machine-generated and therefore display-only. */
const AI_MARKERS = [
  /\b(?:as an ai|ai-generated|generated by|chatgpt|gpt-4|gpt-5|claude|gemini|copilot)\b/iu,
  /本(?:文|内容|回答)(?:由|系)?\s*AI\s*(?:生成|撰写|创作)/u,
  /(?:AI|人工智能)\s*(?:生成|撰写|创作|合成)/u,
  /内容由\s*(?:大模型|AI|人工智能)/u,
]

/** Phrases that indicate the claim is about a counterfeit rather than a genuine article. */
const KO_MARKERS = [
  /\b(?:ko|knock[- ]?off|bootleg|recast|copy)\b/iu,
  /(?:盗版|高仿|仿品|翻模|祖国版|山寨|平替版|散货)/u,
]

/** Parsed whitelist cache. */
let whitelistCache

/**
 * @returns {Promise<any>} the official-subject whitelist.
 */
export async function loadWhitelist() {
  if (whitelistCache === undefined) {
    const { readFile } = await import('node:fs/promises')
    whitelistCache = JSON.parse(await readFile(fileURLToPath(new URL('../data/official-whitelist.json', import.meta.url)), 'utf8'))
  }
  return whitelistCache
}

/**
 * @returns {string} path of the user-confirmed whitelist layer.
 */
export function userWhitelistFile() {
  return dataPath('whitelist-user.json')
}

/**
 * @returns {Promise<any[]>} accounts the user personally confirmed.
 */
export async function loadUserWhitelist() {
  const document = await readJsonIfPresent(userWhitelistFile(), null)
  return Array.isArray(document?.accounts) ? document.accounts : []
}

/**
 * Remember a user-confirmed account so the same prompt never appears twice.
 * @param {object} account - `{ platform, handle, subject?, lightning? }`.
 * @returns {Promise<{ handle: string, total: number }>} confirmation summary.
 */
export async function confirmAccount(account) {
  if (!account || typeof account.handle !== 'string' || account.handle.trim() === '') {
    throw new Error('confirmAccount: handle is required')
  }
  const accounts = await loadUserWhitelist()
  const key = `${account.platform ?? 'unknown'}:${account.handle}`
  const existing = accounts.findIndex((item) => `${item.platform ?? 'unknown'}:${item.handle}` === key)
  const entry = { ...account, confirmedAt: new Date().toISOString() }
  if (existing === -1) accounts.push(entry)
  else accounts[existing] = entry
  await writeJsonAtomic(userWhitelistFile(), { version: 1, accounts })
  return { handle: account.handle, total: accounts.length }
}

/**
 * @param {string} url - candidate URL.
 * @returns {{ domain: string, vpnRequired: boolean, scheme: string }} host facts.
 */
export function hostFacts(url) {
  try {
    const parsed = new URL(url)
    const domain = parsed.hostname.replace(/^www\./u, '')
    return {
      domain,
      scheme: parsed.protocol.replace(':', ''),
      vpnRequired: VPN_DOMAINS.some((item) => domain === item || domain.endsWith(`.${item}`)),
    }
  } catch {
    return { domain: '', scheme: '', vpnRequired: false }
  }
}

/**
 * Match a domain against the official whitelist.
 * @param {string} domain - bare hostname.
 * @returns {any | undefined} the matching subject.
 */
export async function matchSubjectByDomain(domain) {
  if (domain === '') return undefined
  const whitelist = await loadWhitelist()
  return whitelist.subjects.find((subject) => subject.domains.some((item) => domain === item || domain.endsWith(`.${item}`)))
}

/**
 * Classify a Bilibili account.
 *
 * The blue lightning bolt is necessary but not sufficient: an official account
 * must also present a verified subject and an avatar, and its title *and* bio
 * must both read as toy/model content. Anything short of that is returned as
 * `needsUserConfirmation` rather than being silently downgraded.
 *
 * @param {object} account - observed account facts.
 * @param {string} [account.handle] - account display name.
 * @param {'blue'|'yellow'|'none'} [account.lightning] - lightning badge colour, as shown in the account header.
 * @param {string} [account.verifiedSubject] - the 认证主体 text shown on the profile.
 * @param {boolean} [account.hasAvatar] - whether a custom avatar (not the default) is present.
 * @param {string} [account.title] - the account's self-description headline.
 * @param {string} [account.bio] - the account's biography text.
 * @returns {Promise<object>} classification with tier, trust, and reasons.
 */
export async function classifyBilibili(account = {}) {
  const handle = String(account.handle ?? '').trim()
  const lightning = account.lightning === 'blue' || account.lightning === 'yellow' ? account.lightning : 'none'
  const reasons = []
  const whitelist = await loadWhitelist()
  const userConfirmed = await loadUserWhitelist()

  const subjectHit = [...whitelist.subjects, ...userConfirmed.map((item) => ({ subject: item.subject ?? item.handle, aliases: [item.handle] }))]
    .find((subject) => [subject.subject, ...(subject.aliases ?? [])].some((alias) => alias && (handle.includes(alias) || String(account.verifiedSubject ?? '').includes(alias))))

  const combined = `${account.title ?? ''} ${account.bio ?? ''}`
  const toyRelevant = /(?:玩具|模型|高达|钢普拉|腰带|变身|假面|特摄|ガンプラ|ホビー|フィギュア|ドライバー|プラモデル|gunpla|hobby|figure|tokusatsu|rider)/iu.test(combined)
  const offTopicSignals = /(?:优惠券|返利|代购群|加微信|私信出|免费领|点击链接|兼职)/u.test(combined)

  if (lightning === 'blue') {
    reasons.push('账号带蓝闪电（官方认证标识）')
    if (account.verifiedSubject) reasons.push(`认证主体：${account.verifiedSubject}`)
    else reasons.push('未读取到认证主体，需要弹窗确认')
    if (account.hasAvatar) reasons.push('使用自定义头像')
    else reasons.push('未使用自定义头像，需要弹窗确认')
    if (!toyRelevant) reasons.push('标题与简介未同时体现玩具/模型主题')
    if (offTopicSignals) reasons.push('简介含营销或导流特征')
  } else if (lightning === 'yellow') {
    reasons.push('账号为黄闪电（优秀创作者，非官方）')
  } else {
    reasons.push('账号无闪电标识')
  }

  const fullyOfficial = lightning === 'blue' && Boolean(account.verifiedSubject) && account.hasAvatar === true && toyRelevant && !offTopicSignals
  if (fullyOfficial && subjectHit) {
    return {
      accountClass: 'official',
      tier: 3,
      trust: TIERS[2].trust,
      subject: subjectHit.subject,
      needsUserConfirmation: false,
      reasons: [...reasons, `命中官方认证主体白名单：${subjectHit.subject}`],
    }
  }
  if (fullyOfficial && !subjectHit) {
    return {
      accountClass: 'official-unlisted',
      tier: 3,
      trust: TIERS[2].trust - 8,
      subject: account.verifiedSubject,
      needsUserConfirmation: true,
      prompt: '该账号具备蓝闪电与认证主体，但不在白名单中。请确认它是否为官方号，确认后写入白名单。',
      reasons,
    }
  }
  if (lightning === 'blue') {
    return {
      accountClass: 'official-incomplete',
      tier: 6,
      trust: 62,
      needsUserConfirmation: true,
      prompt: '该账号虽有蓝闪电，但认证主体、头像或主题不符，不能直接按官方对待。请人工确认。',
      reasons,
    }
  }
  if (lightning === 'yellow') {
    return { accountClass: 'verified-creator', tier: 8, trust: TIERS[7].trust, needsUserConfirmation: false, reasons }
  }
  return { accountClass: 'plain-creator', tier: 9, trust: TIERS[8].trust, needsUserConfirmation: false, reasons }
}

/**
 * Assess one candidate source end to end.
 *
 * @param {object} source - candidate source facts.
 * @param {string} [source.url] - source URL when it is a web page.
 * @param {string} [source.platform] - bilibili | x | youtube | weibo | wiki | retailer | blog | forum | group.
 * @param {string} [source.title] - source title.
 * @param {string} [source.text] - excerpted body text used for AI/KO marker scans.
 * @param {object} [source.account] - account facts, forwarded to {@link classifyBilibili} for Bilibili.
 * @param {boolean} [source.advertorial] - whether the content reads as sponsored.
 * @returns {Promise<object>} the assessment.
 */
export async function assessSource(source = {}) {
  const facts = source.url ? hostFacts(source.url) : { domain: '', vpnRequired: false, scheme: '' }
  const text = `${source.title ?? ''} ${source.text ?? ''}`
  const flags = {
    aiGenerated: AI_MARKERS.some((pattern) => pattern.test(text)),
    counterfeitMention: KO_MARKERS.some((pattern) => pattern.test(text)),
    vpnRequired: facts.vpnRequired,
    advertorial: source.advertorial === true,
  }

  const subject = await matchSubjectByDomain(facts.domain)
  if (subject) {
    return {
      ...facts,
      flags,
      tier: 1,
      trust: TIERS[0].trust,
      label: TIERS[0].label,
      subject: subject.subject,
      filedable: true,
      displayOnly: false,
      reasons: [`域名属于官方主体：${subject.subject}`],
    }
  }

  if (facts.vpnRequired && source.platform === 'official') {
    return {
      ...facts,
      flags,
      tier: 2,
      trust: TIERS[1].trust,
      label: TIERS[1].label,
      filedable: true,
      displayOnly: false,
      needsVpn: true,
      reasons: ['海外官方账号，需要 VPN 才能核实'],
    }
  }

  if (source.platform === 'bilibili') {
    const classification = await classifyBilibili(source.account ?? {})
    const tier = TIERS[classification.tier - 1]
    const filedable = classification.accountClass === 'official' && !flags.aiGenerated && !flags.advertorial
    return {
      ...facts,
      flags,
      tier: classification.tier,
      trust: classification.trust,
      label: tier.label,
      accountClass: classification.accountClass,
      needsUserConfirmation: classification.needsUserConfirmation,
      prompt: classification.prompt,
      filedable,
      displayOnly: !filedable || classification.tier >= 6,
      reasons: classification.reasons,
    }
  }

  const platformTier = {
    wiki: 6, retailer: 6, blog: 7, forum: 7, group: 10, x: 2, youtube: 2, weibo: 6,
  }[source.platform] ?? 9
  const tier = TIERS[platformTier - 1]
  const displayOnly = platformTier >= 6 || flags.aiGenerated || flags.advertorial
  return {
    ...facts,
    flags,
    tier: platformTier,
    trust: flags.aiGenerated || flags.advertorial ? Math.min(tier.trust, 25) : tier.trust,
    label: tier.label,
    filedable: !displayOnly,
    displayOnly,
    reasons: [
      `平台分级：${tier.label}`,
      ...(flags.aiGenerated ? ['检出 AI 生成标记，只展示不入库'] : []),
      ...(flags.advertorial ? ['疑似推广内容，降权处理'] : []),
      ...(platformTier >= 6 ? ['低于官方层级的来源需要至少两源交叉'] : []),
    ],
  }
}

/**
 * Cross-verify a claim across assessed sources.
 *
 * At least two independent sources must concur, and at least one must be
 * fileable, before the claim may enter the knowledge base.
 * @param {object[]} assessments - results of {@link assessSource}.
 * @param {string} [claim] - the claim under test, echoed for the caller.
 * @returns {{ supported: boolean, independentSources: number, bestTier: number, filedable: boolean, blockers: string[], claim: string }} the verdict.
 */
export function crossVerify(assessments, claim = '') {
  const usable = assessments.filter((item) => item.displayOnly !== true)
  const distinctDomains = new Set(usable.map((item) => item.domain || item.label))
  const bestTier = assessments.reduce((min, item) => Math.min(min, item.tier), Number.POSITIVE_INFINITY)
  const blockers = []
  if (distinctDomains.size < 2) blockers.push('独立来源少于 2 个，按规范只能标「待确认」')
  if (!assessments.some((item) => item.filedable)) blockers.push('没有任何可入库来源（官网/官方号/官方发售列表）')
  if (assessments.some((item) => item.flags?.aiGenerated)) blockers.push('存在 AI 生成内容，只展示不入库')
  if (assessments.some((item) => item.needsVpn)) blockers.push('含需 VPN 核实的来源，需确认已联网核实')
  return {
    claim,
    supported: blockers.length === 0,
    independentSources: distinctDomains.size,
    bestTier: Number.isFinite(bestTier) ? bestTier : 0,
    filedable: blockers.length === 0,
    blockers,
  }
}

/**
 * Build a search plan for a query in the requested market.
 * @param {string} query - search text.
 * @param {'zh'|'en'|'ja'|'ru'} language - market.
 * @param {boolean} [allowBaidu] - whether the unverified Baidu fallback may be offered.
 * @returns {{ engine: string, url: string, note: string, requiresVpn: boolean, unverified: boolean }[]} ordered search entry points.
 * @deprecated Prefer {@link buildSourcePlan}; kept for the search-only path and tests.
 */
export function buildSearchPlan(query, language = 'zh', allowBaidu = false) {
  return buildSourcePlan(query, language, allowBaidu).searches
}

/**
 * Build the full research plan for one item: search entry points, the source
 * hierarchy to walk, and the standing anti-misinformation rules.
 * @param {string} query - item name or product code.
 * @param {'zh'|'en'|'ja'|'ru'} language - market.
 * @param {boolean} [allowBaidu] - whether the unverified Baidu fallback may be offered.
 * @returns {object} the plan.
 */
export function buildSourcePlan(query, language = 'zh', allowBaidu = false) {
  const primary = SEARCH_ENGINES[language] ?? SEARCH_ENGINES.zh
  const encoded = encodeURIComponent(query)
  const searches = [
    { engine: primary.engine, url: primary.url + encoded, note: primary.note, requiresVpn: ['google', 'yandex'].includes(primary.engine), unverified: false },
  ]
  if (language === 'zh' && allowBaidu) {
    searches.push({ engine: 'baidu', url: SEARCH_ENGINES['zh-alt'].url + encoded, note: SEARCH_ENGINES['zh-alt'].note, requiresVpn: false, unverified: true })
  }
  const officialSiteHints = [
    `site:bandai-hobby.net ${query}`,
    `site:tamashiiweb.com ${query}`,
    `site:bandai.co.jp ${query}`,
    `site:gundam.info ${query}`,
  ]
  return {
    query,
    language,
    searches,
    banned: BANNED_ENGINES,
    officialSiteHints: officialSiteHints.map((hint) => ({
      hint,
      url: `${primary.url}${encodeURIComponent(hint)}`,
      requiresVpn: ['google', 'yandex'].includes(primary.engine),
    })),
    hierarchy: TIERS.map((tier) => ({ tier: tier.id, key: tier.key, label: tier.label, note: tier.note })),
    rules: [
      '至少两个独立来源一致才可入库；不足两源一律标「待确认」。',
      'AI 生成内容只展示、不入库。',
      '无闪电或有闪电但主体不符的账号，必须弹窗让用户确认后才按官方对待。',
      '需 VPN 的域名连不上时先弹窗询问用户，等待期间不调用任何模型。',
      '老物按 官网 → 官方发售列表 → 当年官号宣发视频 → 当年帖子/博客 的顺序多平台查。',
    ],
  }
}

/**
 * Classify how an item should be treated in the default versus rich mode.
 * @param {string} line - gunpla | belt.
 * @param {string} grade - line-specific grade key.
 * @param {boolean} richMode - whether 富哥模式 is on.
 * @returns {{ inScope: boolean, tier: string, reason: string }} scope verdict.
 */
export function scopeOf(line, grade, richMode) {
  const richGrades = {
    gunpla: ['PG', 'MGEX', 'MB', 'KAITAI-SHOKI', 'RE100', 'FULLMECHANICS', 'HI-RESOLUTION', 'THIRD-PARTY'],
    belt: ['CSM', 'CS', 'SHOKUGAN', 'GASHAPON', 'THIRD-PARTY'],
  }
  const defaultGrades = {
    gunpla: ['EG', 'HG', 'RG', 'MG', 'SD'],
    belt: ['DX'],
  }
  if ((defaultGrades[line] ?? []).includes(grade)) {
    return { inScope: true, tier: 'default', reason: '大众款，默认范围内' }
  }
  if ((richGrades[line] ?? []).includes(grade)) {
    return richMode
      ? { inScope: true, tier: 'rich', reason: '富哥模式已开启，纳入范围' }
      : { inScope: false, tier: 'rich', reason: '属于富哥模式范围，当前未开启；可在设置页开启' }
  }
  return { inScope: false, tier: 'unknown', reason: '未识别的等级，请手动补型号' }
}
